### ISSUE TITLE
how can i export the maps

### ISSUE THREAD

**Issue by tx19851107** [dundalek/atom-markdown-mindmap#11] opened 2016-06-25 09:31 UTC
it works 
but how can export the created mindmaps 
is there any shortcut to copy it t?

**Comment by dundalek** [comment] 2017-01-16 14:24
Duplicate of https://github.com/dundalek/atom-markdown-mindmap/issues/5, it is now implemented.

**Closed by dundalek** 2017-01-16 14:24 UTC
